FROM alpine:3.18

COPY . /srv
WORKDIR /srv

RUN apk add \
	python3 \
	py3-pip

RUN pip3 install virtualenv && \
	virtualenv .venv

RUN . /srv/.venv/bin/activate && \
	pip install \
	fastapi \
	uvicorn \
	pydantic \
	passlib \
	nltk \
	httpx \
	pytest \
	&& deactivate

ENTRYPOINT . /srv/.venv/bin/activate && \
	uvicorn main:app --reload --host 0.0.0.0 --timeout-keep-alive 400